### ISSUE TITLE
सहजकोड के लिए वेबसाइट पर फेविकॉन आइकॉन बनाएं और जोड़ें

### ISSUE THREAD

**Issue by pradyroy** [sahajcode/sahajcode.github.io#2]
सहजकोड के लिए वेबसाइट पर फेविकॉन आइकॉन बनाएं और जोड़ें: https://realfavicongenerator.net/
<img width="150" alt="sahajcode-icon" src="https://user-images.githubusercontent.com/54105875/202228505-bd0a85fe-ce5f-4859-90ae-8f3f52ac16ab.png">

**Comment by koyeliroy** [comment]
फेव-आइकन RealFaviconGenerator वेबसाइट का उपयोग करके बनाए गए और index.html में जोड़े गए
<img width="321" alt="fav-icon-added" src="https://user-images.githubusercontent.com/56766160/202368641-6c808fdb-4597-41c5-ac56-b79fcba2fc20.png">
