### ISSUE TITLE
कस्टम डोमेन sahajcode.com और sahajcode.in से वेबसाइट सर्व करें

### ISSUE THREAD

**Issue by koyeliroy** [sahajcode/sahajcode.github.io#3]
कस्टम डोमेन sahajcode.com और sahajcode.in से sahajcode.github.io वेबसाइट सर्व करें

**Comment by pradyroy** [comment]
1.) CNAME फ़ाइल sahajcode.github.io रिपॉजिटरी में जोड़ी गयी
2.) sahajcode.com ​​के लिए GODADDY DNS जोन फाइल में बदलाव किए गए हैं
3.) sahajcode.in के लिए GODADDY mein डोमेन फॉरवर्डिंग सेट गया है
https://www.sahajcode.com एवं  https://sahajcode.in लाइव हैं
